### ISSUE TITLE
Loading screen

### ISSUE THREAD

**Issue by FacuBenito** [xulihang/react-barcode-qrcode-scanner#1]
I've been using this package for some days now and I've gotta say it's working like a charm! Truly thankful for this awesome qr barcode scanner!

If you're open to ideas, I think it'd be nice to be able to add a loading screen to the camera since on the initial render I'm getting a white square until the camera actually loads and I'd like to modify it or hide it since I need the camera to match some styling that I already have on my app.

Other than that, this library is working amazingly!

**Comment by xulihang** [comment]
A loading screen is not built-in. You can add your own loading image like what I did in the example: https://github.com/tony-xlh/react-barcode-qrcode-scanner/blob/1e750fa68558e578def763c61ca1fe08841467c6/example/src/App.tsx#L157-L159
